### PR TITLE
Implemented jz, jnz, jmp for ideal case

### PR DESCRIPTION
**Pull request by AndyYou0115**

### CODE REVIEW

**Comment by AndyYou0115** [comment]
Also store and load

**Comment by lixingliu** [comment]
Going to take a look into labels with underscores in them now

**Comment by lixingliu** [comment]
need to take a look into jnz

**Comment by lixingliu** [comment]
also need to change it to sys arg, not input

**Comment by lixingliu** [comment]
need to do store and load, a bit confused bout it

**Comment by lixingliu** [comment]
need to also deal with comments

**Pull request merged**
